# Generated by Django 4.1.7 on 2023-06-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_specialtiestags_admissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialties',
            name='speciality_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.specialtiestags'),
        ),
    ]
