# Generated by Django 4.1.7 on 2023-06-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_specialties_speciality_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialtiesTags',
            new_name='SpecialtiesIds',
        ),
        migrations.RenameField(
            model_name='admissions',
            old_name='speciality_tag',
            new_name='speciality',
        ),
        migrations.RenameField(
            model_name='specialties',
            old_name='speciality_tag',
            new_name='speciality',
        ),
    ]
