# Generated by Django 4.1.7 on 2023-06-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_admissions_speciality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissions',
            old_name='speciality_id',
            new_name='speciality',
        ),
    ]
